//  memberId: userAttribs.id!,
//     address: ctx.request.body.address,
//     city: ctx.request.body.city,
//     state: ctx.request.body.state,
//     zip: ctx.request.body.zip,
//     price: ctx.request.body.price,
//     closing: ctx.request.body.closing,
//     interest: userAttribs.intRate!,
//     term: userAttribs.loanTerm!,
//     down: userAttribs.down!,
//     points: userAttribs.points!,
//     rent: ctx.request.body.rent,
//     taxes: ctx.request.body.taxes,
//     insurance: ctx.request.body.insurance,
//     maint: ctx.request.body.maint,
//     hoa: ctx.request.body.hoa,
//     capExp: ctx.request.body.capExp,

import Joi = require("joi");

export const validatePropertyCreate = Joi.object().keys({
  memberId: Joi.number(),
  address: Joi.string(),
  city: Joi.string(),
  state: Joi.string(),
  zip: Joi.number(),
  price: Joi.number(),
  closing: Joi.number(),
  interest: Joi.number(),
  term: Joi.number(),
  down: Joi.number(),
  points: Joi.number(),
  rent: Joi.number(),
  taxes: Joi.number(),
  insurance: Joi.number(),
  maint: Joi.number(),
  hoa: Joi.number(),
  capExp: Joi.number(),
});
